---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: func-c-rps
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
        autoscaling.knative.dev/metric: "rps"
        autoscaling.knative.dev/target: "10"
        autoscaling.knative.dev/target-utilization-percentage: "70"
        autoscaling.knative.dev/min-scale: "0"
        autoscaling.knative.dev/max-scale: "50"
    spec:
      containers:
      - image: YOUR_DOCKER_USER/function-c:v1
        env:
        - name: WORK_MS
          value: "100"
        ports:
        - containerPort: 8080
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: func-b-rps
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
        autoscaling.knative.dev/metric: "rps"
        autoscaling.knative.dev/target: "10"
        autoscaling.knative.dev/target-utilization-percentage: "70"
        autoscaling.knative.dev/min-scale: "0"
        autoscaling.knative.dev/max-scale: "50"
    spec:
      containers:
      - image: YOUR_DOCKER_USER/function-b:v1
        env:
        - name: NEXT_FUNCTION
          value: "http://func-c-rps.default.svc.cluster.local"
        - name: WORK_MS
          value: "100"
        ports:
        - containerPort: 8080
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: func-a-rps
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
        autoscaling.knative.dev/metric: "rps"
        autoscaling.knative.dev/target: "10"
        autoscaling.knative.dev/target-utilization-percentage: "70"
        autoscaling.knative.dev/min-scale: "0"
        autoscaling.knative.dev/max-scale: "50"
    spec:
      containers:
      - image: YOUR_DOCKER_USER/function-a:v1
        env:
        - name: NEXT_FUNCTION
          value: "http://func-b-rps.default.svc.cluster.local"
        - name: WORK_MS
          value: "100"
        ports:
        - containerPort: 8080